name: Docker Build Main and Deploy to Testing

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    branches: [ main ]
    types: [ completed ]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.prod
        push: true
        secrets: |
          "gh_package_read_token=${{ secrets.GH_PACKAGE_READ_TOKEN }}"
        tags: | 
           ghcr.io/mlibrary/${{ secrets.IMAGE_NAME }}:latest
           ghcr.io/mlibrary/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
    - name: Deploy to testing
      uses: mlibrary/deploy-to-kubernetes@v2
      with:
        registry_token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/mlibrary/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
        cluster_ca: ${{ secrets.HATCHER_CLUSTER_CA }}
        cluster_server: https://hatcher.kubernetes.lib.umich.edu
        namespace_token: ${{ secrets.HATCHER_TOKEN }}
        namespace: ${{ secrets.NAMESPACE }}
        type: cronjob
        cronjob_name: send-alma-sms
